// Code generated by goctl. DO NOT EDIT!
// Source: book.proto

package server

import (
	"context"

	"bookstore/rpc/book/book"
	"bookstore/rpc/book/internal/logic"
	"bookstore/rpc/book/internal/svc"
)

type BookServer struct {
	svcCtx *svc.ServiceContext
}

func NewBookServer(svcCtx *svc.ServiceContext) *BookServer {
	return &BookServer{
		svcCtx: svcCtx,
	}
}

func (s *BookServer) Add(ctx context.Context, in *book.AddReq) (*book.AddResp, error) {
	l := logic.NewAddLogic(ctx, s.svcCtx)
	return l.Add(in)
}

func (s *BookServer) Update(ctx context.Context, in *book.AddReq) (*book.AddResp, error) {
	l := logic.NewUpdateLogic(ctx, s.svcCtx)
	return l.Update(in)
}
